// Generated by CoffeeScript 1.6.3
(function() {
  module.exports.format_date = function(date) {
    var am, meridiem, new_date;
    meridiem = /\ (a|p)m/;
    new_date = new Date(date.replace(meridiem, ''));
    if ((date.match(meridiem)) != null) {
      am = (date.match(/\ am/)) != null;
      if (am && new_date.getHours() === 12) {
        new_date.setHours(0);
      }
      if ((!am) && new_date.getHours() !== 12) {
        new_date.setHours(new_date.getHours() + 12);
      }
    }
    return new_date;
  };

}).call(this);
