// Generated by CoffeeScript 1.6.3
(function() {
  var DEFAULT_FOLDER, Reports, fs, path, _;

  _ = require('underscore');

  fs = require('fs');

  path = require('path-extra');

  DEFAULT_FOLDER = path.join(path.homedir(), 'Dropbox/Apps/Reporter-App/');

  module.exports = Reports = function(options) {
    this.options = options != null ? options : {
      directory: DEFAULT_FOLDER
    };
  };

  (function() {
    return this.list = function(options) {
      var connections, directory, impetus, reports;
      reports = [];
      directory = this.options.directory;
      fs.readdirSync(directory).forEach(function(file) {
        var data, snapshots;
        if (file.match(/.json$/)) {
          data = fs.readFileSync(path.join(directory, file));
          snapshots = JSON.parse(data).snapshots;
          return _.each(snapshots, function(report) {
            return reports.push(report);
          });
        }
      });
      if (options != null) {
        if (options.type != null) {
          impetus = ['button', 'buttonAsleep', 'notification', 'sleep', 'wake'];
          reports = _.filter(reports, function(r) {
            return (r.reportImpetus != null) && r.reportImpetus === impetus.indexOf(options.type);
          });
        }
        if (options.connection != null) {
          connections = ['cellular', 'wifi', 'none'];
          reports = _.filter(reports, function(r) {
            return r.connection === connections.indexOf(options.connection);
          });
        }
      }
      return reports;
    };
  }).call(Reports.prototype);

}).call(this);
